# Generated by Django 3.1.7 on 2021-04-25 04:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_chatgroup_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='users',
            field=models.ManyToManyField(related_name='user_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
